###
POST {{oc}}/api/batch
Content-Type: text/x-yaml

< empty.yml

###
POST {{oc}}/api/object-construct
Accept: application/json
Content-Type: application/json

{
  "cls": "example.empty",
  "embeddedRecord": {},
  "labels": ["test-empty"],
  "keys": [],
  "overrideUrls": {}
}

> {%
client.global.set("obj_0_id", response.body.object.id)
%}
###
GET {{cds}}/{{obj_0_id}}
###
GET {{cds}}/{{obj_0_id}}:example.empty.function()/text?await=true
###
GET {{cds}}/{{obj_0_id}}:example.empty.function()
###
GET {{tm}}/oal/{{obj_0_id}}:example.empty.function()/tmp
###
GET {{cds}}/d8e51bdc-bdf5-42a9-bb8b-94060a336e00
