###
POST {{cds}}/api/packages
Content-Type: text/x-yaml

< record.yml

###
POST {{cds}}/api/object-construct
Accept: application/json
Content-Type: application/json

{
  "cls": "example.record"
}

> {%
client.global.set("obj_0_id", response.body.object.id)
%}
###
GET {{cds}}/oal/{{obj_0_id}}
###
GET {{cds}}/oal/{{obj_0_id}}:json-update?async=true

> {%
client.global.set("obj_1_id", response.body.output.id)
%}

###
GET {{cds}}/oal/{{obj_1_id}}

###
GET {{cds}}/oal/{{obj_1_id}}:json-update()

> {%
  client.global.set("obj_1_id", response.body.output.id)
%}
###
GET {{cds}}/oal/{{obj_0_id}}:chain?async=true

> {%
  client.global.set("obj_1_id", response.body.output.id)
%}
