###
POST {{oc}}/api/batch
Content-Type: text/x-yaml

< text.yml

###
POST {{oc}}/api/object-construct
Accept: application/json
Content-Type: application/json

{
  "cls": "example.text",
  "embeddedRecord": {},
  "labels": ["test-empty"],
  "keys": ["text"],
  "overrideUrls": {}
}

> {%
client.global.set("obj_0_id", response.body.object.id)
client.global.set("upload_text", response.body.uploadUrls.text)
%}
###
PUT {{upload_text}}
Content-Type: text/plain

< ../../../oaas-load-test/test-files/test-10k.txt

###
GET {{cdn}}/{{obj_0_id}}/text
###
GET {{cdn}}/{{obj_0_id}}:example.text.concat()(APPEND=NEW_TEXT,PERSIST=false)/text
###
GET {{cdn}}/{{obj_0_id}}:example.text.concat()(APPEND=NEW_TEXT)/text
###
GET {{tm}}/oal/{{obj_0_id}}:example.text.concat()(APPEND=NEW_TEXT,PERSIST=false)/text
###
GET http://task-manager.msc.knative.10.131.36.27.nip.io/oae/{{obj_0_id}}:example.text.concat()(APPEND=NEW_TEXT,PERSIST=false)/text
