###
POST {{cds}}/api/batch
Content-Type: text/x-yaml

< video.yml

###
POST {{cds}}/api/object-construct
Accept: application/json
Content-Type: application/json

{
  "cls": "example.video",
  "embeddedRecord": {
    "title": "title",
    "desc": "description..."
  },
  "labels": ["test"],
  "overrideUrls": {
    "video": "{{base_url}}/test2-30s.mp4"
  }
}

> {%
client.global.set("obj_0_id", response.body.object.id)
%}

###
GET {{cds}}/{{obj_0_id}}:transcode()(RESOLUTION=720x480)/video

###
GET {{cds}}/{{obj_0_id}}:transcode()(RESOLUTION=no,VCODEC=copy,FORMAT=mkv)/video
