###
POST {{oc}}/api/batch
Content-Type: text/x-yaml

< video.yml

###
POST {{oc}}/api/object-construct
Accept: application/json
Content-Type: application/json

{
  "cls": "example.video",
  "embeddedRecord": {
    "title": "title",
    "desc": "description..."
  },
  "labels": ["test"],
  "overrideUrls": {
    "video": "{{base_url}}/test2-30s.mp4"
  }
}

> {%
client.global.set("obj_0_id", response.body.object.id)
%}

###
GET {{cds}}/{{obj_0_id}}:transcode()(RESOLUTION=720x480)/video

###
GET {{cds}}/{{obj_0_id}}:transcode()(RESOLUTION=no,VCODEC=copy,FORMAT=mkv)/video

###
GET {{cds}}/{{obj_0_id}}:tohls()()

> {%
client.global.set("obj_1_id", response.body.id)
%}

###
GET {{oc}}/api/objects/{{obj_1_id}}

###
GET {{cds}}/{{obj_1_id}}/video.m3u8

###
#GET {{cds}}/{{obj_1_id}}:blur()()
GET {{cds}}/{{obj_1_id}}:grayscale()()
#GET {{cds}}/{{obj_1_id}}:mirror()()

> {%
client.global.set("obj_2_id", response.body.id)
%}

###
GET {{oc}}/api/objects/{{obj_2_id}}

###
GET {{cds}}/{{obj_2_id}}/video.m3u8
