###
POST {{oc}}/api/batch
Content-Type: text/x-yaml

< video.yml

###
POST {{oc}}/api/object-construct
Accept: application/json
Content-Type: application/json

{
  "cls": "example.video",
  "embeddedRecord": {},
  "labels": ["test"],
  "keys": ["video"],
  "overrideUrls": {}
}

> {%
client.global.set("obj_0_id", response.body.object.id)
client.global.set("upload_url", response.body.uploadUrls.video)
%}

###
PUT {{upload_url}}
Content-Type: application/octet-stream

< ../../../oaas-load-test/test-files/test-1s.mp4

###
GET {{cds}}/{{obj_0_id}}:transcode()(RESOLUTION=720x480)/video

###
GET {{cds}}/{{obj_0_id}}:transcode()(RESOLUTION=no,VCODEC=copy,FORMAT=mkv)/video
