{
 "title": "Oparaca",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "crId",
    "label": "CR",
    "query": {
     "query": "label_values(oprc_invocation_seconds_count,crId)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_usage_bytes{pod=~\"cr-$crId.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{pod=~\"cr-$crId-.*\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Invoker requests per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (crId) (rate(oprc_invocation_seconds_count{crId=\"$crId\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Invocation Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (crId, le) (rate(oprc_invocation_seconds_bucket{crId=\"$crId\"}[1m])))",
     "legendFormat": "{{ crId }} (p95)"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (crId, le) (rate(oprc_invocation_seconds_bucket{crId=\"$crId\"}[1m])))",
     "legendFormat": "{{ crId }} (p50)"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (crId, le) (rate(oprc_invocation_seconds_bucket{crId=\"$crId\"}[1m])))",
     "legendFormat": "{{ crId }} (p99)"
    }
   ]
  }
 ]
}