@startuml
'https://plantuml.com/sequence-diagram


actor Client
participant ObjectController
participant ContentDeliveryServer
queue ResourceRequestQueue
participant TaskGenerator
queue TaskQueue
queue TaskCompletionEvents
participant TaskProvisioner
participant K8sApiServer
collections JobPod
database Storage


Client -> ObjectController: function call request
ObjectController -> ObjectController: update state
ObjectController -> Client:
...
Client -> ContentDeliveryServer: request resource file
ContentDeliveryServer -> ResourceRequestQueue: put to queue
ResourceRequestQueue -> TaskGenerator: receive request
TaskGenerator -> ObjectController: load context
ObjectController -> TaskGenerator:
TaskGenerator -> TaskQueue: create task
TaskQueue -> TaskProvisioner: receive task
TaskProvisioner -> K8sApiServer: submit k8s job
K8sApiServer -> JobPod: create job pod
JobPod -> Storage: load input resource
Storage -> JobPod
JobPod -> JobPod: execute task
JobPod -> Storage: persist output resource
JobPod -> K8sApiServer: acknowledge job completion
K8sApiServer -> TaskProvisioner: receive job completion event
TaskProvisioner -> TaskCompletionEvents: submit event
TaskCompletionEvents -> ContentDeliveryServer: receive event
ContentDeliveryServer -> Storage: load resource
Storage -> ContentDeliveryServer:
ContentDeliveryServer -> Client: reply with resource
@enduml
