@startuml
'https://plantuml.com/sequence-diagram


actor client
participant objectController
participant contentDeliveryServer
queue ResourceRequestQueue
participant TaskGenerator
queue taskQueue
queue taskCompletionBroker
participant JobProvisioner
participant K8sApiServer
collections JobPod
database storage


client -> objectController: function call request
objectController -> objectController: update state
objectController -> client:
...
client -> contentDeliveryServer: request resource file
contentDeliveryServer -> ResourceRequestQueue: put to queue
ResourceRequestQueue -> TaskGenerator: receive request
TaskGenerator -> objectController: load context
objectController -> TaskGenerator:
TaskGenerator -> taskQueue: create task
taskQueue -> JobProvisioner: receive task
JobProvisioner -> K8sApiServer: submit job
K8sApiServer -> JobPod: create job pod
JobPod -> storage: load input resource
storage -> JobPod
JobPod -> JobPod: execute task
JobPod -> storage: put output resource
JobPod -> K8sApiServer: acknowledge job completion
K8sApiServer -> JobProvisioner: receive job completion event
JobProvisioner -> taskCompletionBroker: submit event
taskCompletionBroker -> contentDeliveryServer: receive event
contentDeliveryServer -> storage: load resource
storage -> contentDeliveryServer:
contentDeliveryServer -> client: reply with resource
@enduml
