apiVersion: v1
kind: Service
metadata:
  name: invoker-ping
spec:
  # Has to be None
  clusterIP: None
  # Set to true so that members can be discovered without interfering with your readiness probe logic
  publishNotReadyAddresses: true
  sessionAffinity: None
  type: ClusterIP
  selector: {}
  ports:
    - name: ping
      protocol: TCP
      port: 8888
      targetPort: 8888
