apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-adapter
spec:
  replicas: 1
  selector:
    matchLabels: {} #to be injected
  template:
    metadata:
      labels: {} #to be injected
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels: {} #to be injected
                topologyKey: "kubernetes.io/hostname"
      containers:
        - name: storage-adapter
          image: ghcr.io/hpcclab/oaas/storage-adapter:latest
          ports:
            - containerPort: 8080
              name: http
          resources:
            limits:
              memory: 2G
            requests:
              cpu: '0.1'
              memory: 256M
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/live
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 10
            httpGet:
              path: /q/health/ready
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 3
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
