"%dev":
  oprc:
    log: DEBUG
  quarkus:
    http:
      port: 8093
    console:
      color: true

oprc:
  log: INFO
  env: |
    OPRC_DB_PKG_HOST=localhost
    OPRC_DB_PKG_PORT=8529
    OPRC_DB_PKG_USER=root
    OPRC_DB_DEFAULT_HOST=localhost
    OPRC_DB_DEFAULT_PORT=8529
    OPRC_DB_DEFAULT_USER=root
    OPRC_DB_S3DEFAULT_URL=http://localhost:9090
    OPRC_DB_S3DEFAULT_BUCKET=oaas-bkt
    OPRC_DB_S3DEFAULT_PUBLICURL=http://localhost:9090
    OPRC_DB_S3DEFAULT_USER=minio_access_key
    OPRC_DB_S3DEFAULT_PASS=minio_secret_key

quarkus:
  s3:
    devservices:
      enabled: false
  http:
    access-log:
      enabled: true
      pattern: '"%r" %s %b %{RESPONSE_TIME} ms'
      exclude-pattern: /q/.*
    record-request-start-time: true
  vertx:
    prefer-native-transport: true
  container-image:
    image: ${ci.registry.image:oaas}/storage-adapter${tag:}
  jib:
    base-jvm-image: eclipse-temurin:17-jre-ubi9-minimal
  log:
    category:
      "org.hpcclab.oaas":
        level: ${oprc.log}
