apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: oaas
spec:
  kafka:
    template:
      pod:
        metadata:
          labels:
            cluster: oaas-kafka
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                podAffinityTerm:
                  labelSelector:
                    matchLabels:
                      cluster: oaas-kafka
                  topologyKey: "kubernetes.io/hostname"
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
      - name: external
        port: 9094
        type: nodeport
        tls: false
        configuration:
          bootstrap:
            nodePort: 31000
          brokers:
            - broker: 0
              nodePort: 31001

    resources:
      requests:
        cpu: "0.5"
        memory: 512M
      limits:
        cpu: "0.5"
        memory: 512M
    storage:
      type: persistent-claim
      size: 1Gi
      deleteClaim: true
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
  zookeeper:
    replicas: 1
    storage:
      type: persistent-claim
      size: 1Gi
      deleteClaim: true
    resources:
      requests:
        cpu: "0.25"
        memory: 256M
      limits:
        cpu: "0.5"
        memory: 512M
  entityOperator:
