= OaaS: Single Node Deployment
:toc:
:toc-placement: preamble
:toclevels: 2

// Need some preamble to get TOC:
{empty}

== Introduction
This guide is for deploying Oparac system on the local Kubernetes (ex. kind, k3d).

== OaaS Installation
=== Prerequisites

* JDK21 (if you want to build the project)

* https://github.com/casey/just[*just*]

* Clone this project.
+
[source,bash]
----
git clone https://github.com/hpcclab/OaaS.git
cd OaaS
----

* Kubernetes
** Container runtime (Docker or Podman)
** Create via k3d
+
[source,bash]
----
k3d cluster create -p "9090:80@loadbalancer"
# or using just (after clone this project)
just k3d-create
----

* Kubernetes-related commandline tools
** *kubectl*
** *helm*




=== Build images
To ensure that you use the images of current project, you may have to build the container images yourself.

Use `mvnw` command to build the project and container images.

[source,bash]
----
./mvnw package -DskipTests "-Dquarkus.container-image.build=true"
# OR using just if you have mvnd
just build-image
----
Load images to k3d runtime.
[source,bash]
----
docker images --format json | jq -r .Repository | grep ghcr.io/hpcclab/oaas | grep -v fn-py | xargs k3d image import
----

=== Install dependencies

Use `just` command to install dependencies

[source,bash]
----
just k8s-deploy-preq
just k8s-deploy-deps
----

This command will do the following steps:

. Create `oaas` namespace

. Knative


. Kafka
** Open Kafka UI at `http://kui.127.0.0.1.nip.io:9090`

. MinIO (S3-compatible storage)
** Open the web console at `http://minio.127.0.0.1.nip.io:9090` and login with `minio_access_key` as a user and `minio_secret_key` as a password.

. ArangoDB
** Open the web console at `http://arg.127.0.0.1.nip.io:9090` and login with `root` as a user and `changeme` as a password.

=== Install and Access OaaS
. Install OaaS
+
[source,bash]
----
kubectl apply -n oaas -k deploy/oaas/local
----
. Wait until all pod is ready
+
[source,bash]
----
kubectl get pod -n oaas -w
----
. Access OaaS via link:../../cli/README.adoc[CLI]
+
[source,bash]
----
ocli ctx set --inv=http://inv.oaas.127.0.0.1.nip.io:9090 --pm=http://pm.oaas.127.0.0.1.nip.io:9090
----
.. package manager: `http://pm.oaas.127.0.0.1.nip.io:9090`
.. Invoker: `http://inv.oaas.127.0.0.1.nip.io:9090`


== Troubleshooting
// * Depend on The distribution of Kubernetes, the IP address of Kube DNS might not be the same. If it isn't `10.96.0.10`, the content delivery service will not work. So, you have to find the correct one and replace `10.96.0.10` in link:../oaas/base/cds.yml[]
* In the case that you can not access Kubernetes via localhost, you need to change the hostname of `*.127.0.0.1.nip.io` to match your setup.
** link:oaas-ingress.yml[]
** link:minio.yml[]
