"%test":
  quarkus:
    console:
      color: true
    log:
      min-level: TRACE
  oaas:
    log: TRACE
    oc:
      orbitEnabled: false

"%dev":
  quarkus:
    console:
      color: true
    http:
      port: 8088
  oaas:
    log: DEBUG

"%prod":
  oaas:
    oc:
      kafkaEnabled: true

oaas:
  oc:
    clsProvisionTopic: oaas-cls
    kafkaEnabled: false
    fnProvisionTopic: oaas-fn
    orbitManagerHost: localhost
    orbitManagerPort: 8091
  log: INFO
  name: class-manager

oprc:
  env: |
    OPRC_DB_PKG_HOST=localhost
    OPRC_DB_PKG_PORT=8529
    OPRC_DB_PKG_USER=root


quarkus:
  http:
    access-log:
      enabled: true
      pattern: '"%r" %s %b %{RESPONSE_TIME} ms'
      exclude-pattern: /q/.*
    record-request-start-time: true
  vertx:
    prefer-native-transport: true
  swagger-ui:
    always-include: true
  smallrye-openapi:
    store-schema-directory: ../doc/oc
    enable: true
  log:
    category:
      "org.hpcclab.oaas":
        level: ${oaas.log}
  container-image:
    image: ${ci.registry.image:oaas}/${oaas.name}${tag:}
  micrometer:
    export:
      json:
        enabled: true
        path: jsonmetrics
  native:
    resources:
      includes:
        - builtin/**
  rest-client:
    allocation-api:
      url: ${oaas.oc.storageAdapterUrl}
  kafka:
    devservices:
      enabled: false

  grpc:
    clients:
      orbit-manager:
        use-quarkus-grpc-client: true
        host: ${oaas.orbit.clsManagerHost}
        port: ${oaas.orbit.clsManagerPort}
mp:
  messaging:
    outgoing:
      fnProvisions:
        enabled: ${oaas.oc.kafkaEnabled}
        connector: smallrye-kafka
        topic: ${oaas.oc.fnProvisionTopic}
        value:
          serializer: io.quarkus.kafka.client.serialization.ObjectMapperSerializer
      clsProvisions:
        enabled: ${oaas.oc.kafkaEnabled}
        connector: smallrye-kafka
        topic: ${oaas.oc.clsProvisionTopic}
        value:
          serializer: io.quarkus.kafka.client.serialization.ObjectMapperSerializer
