###
POST {{oc}}/api/functions?update=true
Content-Type: text/x-yaml

- name: test.dummy.resource
  type: TASK
  outputCls: builtin.basic.file
  validation: {}
  task: {}
- name: test.dummy.compound
  type: MACRO
  outputCls: builtin.basic.compound
  validation: {}
  macro:
      steps:
        - funcName: builtin.logical.copy
          target: obj1
          as: new_obj1
          inputRefs: []
        - funcName: builtin.logical.copy
          target: obj2
          as: new_obj2
          inputRefs: []
      exports:
        - from: new_obj1
          as: obj1
        - from: new_obj2
          as: obj2
###
POST {{oc}}/api/objects
Accept: application/json
Content-Type: application/json

{
  "type": "RESOURCE",
  "cls": "builtin.basic.file",
  "state": {
    "type": "FILE",
    "baseUrl": "http://test/test.ts"
  }
}

> {%
client.global.set("obj1_id", response.body.id)
%}

###
POST {{oc}}/api/objects
Accept: application/json
Content-Type: application/json

{
  "type": "RESOURCE",
  "cls": "builtin.basic.file",
  "state": {
    "type": "FILE",
    "baseUrl": "http://test/test.ts"
  }
}

> {%
client.global.set("obj2_id", response.body.id)
%}

###

POST {{oc}}/api/objects
Accept: application/json
Content-Type: application/json

{
  "type": "COMPOUND",
  "cls": "builtin.basic.compound",
  "members": [
    {
      "name": "obj1",
      "object": "{{obj1_id}}"
    },
    {
      "name": "obj2",
      "object": "{{obj2_id}}"
    }
  ],
  "functions": [{
    "access": "PUBLIC",
    "function": "test.dummy.compound"
  }]
}

> {%
client.global.set("compound_id", response.body.id)
%}

###

GET {{oc}}/api/objects/{{compound_id}}/deep
Accept: application/json

###
POST {{oc}}/api/objects/{{compound_id}}/r-exec
Accept: application/json
Content-Type: application/json

{
  "target": "{{compound_id}}",
  "functionName": "test.dummy.compound"
}
