###
POST {{oc}}/api/objects
Accept: application/json
Content-Type: application/json

{
  "type": "RESOURCE",
  "state": {
    "type": "FILE",
    "url": "{{m3u8_url}}"
  }
}

> {%
client.global.set("m3u8_id", response.body.id)
%}

###
POST {{oc}}/api/objects
Accept: application/json
Content-Type: application/json

{
  "type": "RESOURCE",
  "functions": [
    "builtin.hls.ts.transcode"
  ],
  "state": {
    "type": "SEGMENTABLE",
    "url": "{{segments_url}}",
    "groupId": "test"
  }
}

> {%
client.global.set("segments_id", response.body.id)
%}

###

POST {{oc}}/api/objects
Accept: application/json
Content-Type: application/json

{
  "type": "COMPOUND",
  "functions": [
    "builtin.hls.macro.transcode"
  ],
  "members": {
    "m3u8": "{{m3u8_id}}",
    "segments": "{{segments_id}}"
  }
}

> {%
client.global.set("hls_id", response.body.id)
%}

###


POST {{oc}}/api/objects/{{hls_id}}/r-exec
Accept: application/json
Content-Type: application/json

{
  "target": "{{hls_id}}",
  "functionName": "builtin.hls.macro.transcode"
}

> {%
client.global.set("hls2_id", response.body.id)
client.global.set("hls2_m3u8", response.body.members.m3u8)
client.global.set("hls2_segments", response.body.members.segments)
%}

###
GET {{oc}}/api/objects/{{hls2_segments}}

###
POST {{tg}}/api/tasks
Accept: application/json
Content-Type: application/json

{
  "ownerObjectId": "{{hls2_segments}}",
  "requestFile": "segment-0000.ts"
}


###
GET {{s3}}/{{hls2_segments}}/segment-0000.ts
