POST http://kafka-bridge.10.131.36.27.nip.io/topics/request
Content-Type: application/vnd.kafka.json.v2+json

{
  "records": [
    {
      "key": "test",
      "value": {
        "ownerObjectId": "test",
        "requestFile": "t-01.ts"
      }
    },
    {
      "key": "test",
      "value": {
        "ownerObjectId": "test",
        "requestFile": "t-02.ts"
      }
    },
    {
      "key": "test",
      "value": {
        "ownerObjectId": "test",
        "requestFile": "t-03.ts"
      }
    },
    {
      "key": "test",
      "value": {
        "ownerObjectId": "test",
        "requestFile": "t-04.ts"
      }
    },
    {
      "key": "test",
      "value": {
        "ownerObjectId": "test",
        "requestFile": "t-05.ts"
      }
    },
    {
      "key": "test",
      "value": {
        "ownerObjectId": "test",
        "requestFile": "t-06.ts"
      }
    }
  ]
}

###
POST http://kafka-bridge.10.131.36.27.nip.io/topics/request
Content-Type: application/vnd.kafka.json.v2+json

{
  "records": [
    {
      "key": "test",
      "value": {
        "ownerObjectId": "ttt",
        "requestFile": "t-01.ts"
      }
    },
    {
      "key": "test",
      "value": {
        "ownerObjectId": "ttt",
        "requestFile": "t-02.ts"
      }
    },
    {
      "key": "test",
      "value": {
        "ownerObjectId": "ttt",
        "requestFile": "t-03.ts"
      }
    },
    {
      "key": "test",
      "value": {
        "ownerObjectId": "ttt",
        "requestFile": "t-04.ts"
      }
    },
    {
      "key": "test",
      "value": {
        "ownerObjectId": "ttt",
        "requestFile": "t-05.ts"
      }
    },
    {
      "key": "test",
      "value": {
        "ownerObjectId": "ttt",
        "requestFile": "t-06.ts"
      }
    }
  ]
}
