###
POST {{oc}}/api/batch
Content-Type: text/x-yaml

functions:
  - name: example.concat
    type: TASK
    outputCls: example.text
    validation:
      additionalInputs:
        - requiredClass: example.text
    task:
      type: EPHEMERAL
      image: core.harbor.10.131.36.27.nip.io/oaas/ubi
      #    image: curlimages/curl
      commands:
        - /bin/sh
        - '-c'
      containerArgs:
        - |
          curl -o tmp_file $MAIN_RESOURCE_BASE_URL/$MAIN_RESOURCE_FILE
          curl -o input_0_file $INPUT_0_RESOURCE_BASE_URL/$INPUT_0_RESOURCE_FILE
          cat input_0_file >> tmp_file
          curl -T tmp_file $OUTPUT_RESOURCE_BASE_URL/$TARGET
      argsToEnv: true
classes:
  - name: example.text
    stateType: FILE
    objectType: RESOURCE
    functions:
    - access: PUBLIC
      function: builtin.logical.copy
    - access: PUBLIC
      function: example.concat

###
PUT  {{s3}}/test-resource/obj_0
Content-Type: text/plain

OBJECT 0 TEXT |

###
PUT  {{s3}}/test-resource/obj_1
Content-Type: text/plain

OBJECT 1 TEXT |

###
POST {{oc}}/api/objects
Accept: application/json
Content-Type: application/json

{
  "type": "RESOURCE",
  "cls": "example.text",
  "state": {
    "type": "FILE",
    "baseUrl": "{{s3}}/test-resource",
    "file": "obj_0"
  }
}

> {%
client.global.set("obj_0_id", response.body.id)
%}
###

POST {{oc}}/api/objects
Accept: application/json
Content-Type: application/json

{
  "type": "RESOURCE",
  "cls": "example.text",
  "state": {
    "type": "FILE",
    "baseUrl": "{{s3}}/test-resource",
    "file": "obj_1"
  }
}

> {%
client.global.set("obj_1_id", response.body.id)
%}

###
POST {{oc}}/api/objects/{{obj_0_id}}/exec
Accept: application/json
Content-Type: application/json

{
  "target": "{{obj_0_id}}",
  "functionName": "example.concat",
  "args": {
    "TARGET": "text"
  },
  "additionalInputs": ["{{obj_1_id}}"]
}

> {%
client.global.set("obj_2_id", response.body.id)
%}

###
GET {{cdn}}/{{obj_2_id}}/text

###
GET {{s3}}/{{obj_2_id}}/text
