###
POST {{oc}}/api/batch
Content-Type: text/x-yaml

functions:
  - name: example.text.concat
    type: TASK
    outputCls: example.text
    validation:
      additionalInputs:
        - requiredClass: example.text
    task:
      type: EPHEMERAL
      image: core.harbor.10.131.36.27.nip.io/oaas/ubi
      commands:
        - /bin/sh
        - '-c'
      outputFileNames:
        - text
      containerArgs:
        - |
          curl -s -o tmp_file $MAIN_RESOURCE_BASE_URL/$MAIN_RESOURCE_FILE_0
          echo "Download main file $MAIN_RESOURCE_BASE_URL/$MAIN_RESOURCE_FILE_0"
          curl -s -o input_0_file $INPUT_0_RESOURCE_BASE_URL/$INPUT_0_RESOURCE_FILE_0
          echo "Download input 0 file $INPUT_0_RESOURCE_BASE_URL/$INPUT_0_RESOURCE_FILE_0"
          cat input_0_file >> tmp_file
          echo "concat string"
          curl -s -T tmp_file $OUTPUT_RESOURCE_BASE_URL/$OUTPUT_RESOURCE_FILE_0
          echo "Upload file to $OUTPUT_RESOURCE_BASE_URL/$OUTPUT_RESOURCE_FILE_0"
      argsToEnv: true
classes:
  - name: example.text
    stateType: FILE
    objectType: RESOURCE
    functions:
      - access: PUBLIC
        function: builtin.logical.copy
      - access: PUBLIC
        function: example.text.concat

###
PUT  {{s3}}/test-resource/obj_0
Content-Type: text/plain

OBJECT 0 TEXT |

###
PUT  {{s3}}/test-resource/obj_1
Content-Type: text/plain

OBJECT 1 TEXT |

###
POST {{oc}}/api/objects
Accept: application/json
Content-Type: application/json

{
  "type": "RESOURCE",
  "cls": "example.text",
  "state": {
    "type": "FILE",
    "baseUrl": "{{s3}}/test-resource",
    "files": ["obj_0"]
  }
}

> {%
client.global.set("obj_0_id", response.body.id)
%}
###

POST {{oc}}/api/objects
Accept: application/json
Content-Type: application/json

{
  "type": "RESOURCE",
  "cls": "example.text",
  "state": {
    "type": "FILE",
    "baseUrl": "{{s3}}/test-resource",
    "files": ["obj_1"]
  }
}

> {%
client.global.set("obj_1_id", response.body.id)
%}

###
POST {{oc}}/api/objects/{{obj_0_id}}/exec
Accept: application/json
Content-Type: application/json

{
  "target": "{{obj_0_id}}",
  "functionName": "example.text.concat",
  "args": {
    "TARGET": "txt"
  },
  "additionalInputs": ["{{obj_1_id}}"]
}

> {%
client.global.set("obj_2_id", response.body.id)
%}

###
#GET {{cdn}}/{{obj_2_id}}/text

###
GET {{s3}}/{{obj_2_id}}/text

