###
POST {{oc}}/api/batch
Content-Type: text/x-yaml

< video.yml


###
POST {{oc}}/api/objects
Accept: application/json
Content-Type: application/json

{
  "cls": "example.video",
  "state": {
    "type": "FILE",
    "baseUrl": "{{base_url}}",
    "keys": [
        "test-1s.mp4"
    ]
  }
}

> {%
client.global.set("obj_0_id", response.body.id)
%}

###
GET {{cdn}}/{{obj_0_id}}:example.video.transcode-durable()(RESOLUTION=720x480)/video.mp4?await=true
