###
POST {{oc}}/api/batch
Content-Type: text/x-yaml

< video.yml


###
POST {{oc}}/api/objects
Accept: application/json
Content-Type: application/json

{
  "cls": "example.video",
  "state": {
    "type": "FILE",
    "baseUrl": "{{base_url}}",
    "keys": [
        "test-10s.mp4"
    ]
  }
}

> {%
client.global.set("obj_0_id", response.body.id)
%}

###
POST {{oc}}/api/objects/{{obj_0_id}}/exec
Accept: application/json
Content-Type: application/json

{
  "target": "{{obj_0_id}}",
  "functionName": "example.video.transcode-durable",
  "args": {
    "RESOLUTION": "720x480"
  }
}

> {%
client.global.set("obj_1_id", response.body.id)
%}

###
GET {{cdn}}/{{obj_1_id}}/video.mp4
