apiVersion: v1
kind: Service
metadata:
  name: invoker
spec:
  selector: {}
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
    - name: infinispan
      protocol: TCP
      port: 11222
      targetPort: 11222
