apiVersion: v1
kind: Service
metadata:
  name: storage-adapter
  labels:
    app: storage-adapter
spec:
  selector: {}
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
