#!/usr/bin/env just --justfile
mvn := "mvnd"
version := "999-SNAPSHOT"
set windows-shell := ["powershell.exe", "-NoLogo", "-Command"]

# maven build
build options="":
    ./mvnw "{{options}}" package

# maven build without tests
build-no-test options="":
  {{mvn}} "{{options}}" package -DskipTests

# maven build without tests
build-fast-jar options="":
  {{mvn}} "{{options}}" "-Dquarkus.package.jar.type=fast-jar" package -DskipTests

# maven build without tests
build-uber-jar options="":
  {{mvn}} "{{options}}" "-Dquarkus.package.jar.type=uber-jar" package -DskipTests

# dependencies tree for compile
dependencies:
    ./mvnw dependency:tree

# display updates
updates:
    ./mvnw versions:display-dependency-updates

build-native:
    ./mvnw "-Dquarkus.package.jar.type=fast-jar" install -Pnative -DskipTests

build-native-container:
    ./mvnw "-Dquarkus.package.jar.type=fast-jar" install -Pnative -DskipTests -Dquarkus.native.container-build=true

jbang-install:
    jbang app install --name=ocli --force target/quarkus-app/quarkus-run.jar

build-native-window:
    cmd /c 'call "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\Build\vcvars64.bat" && ./mvnw "-Dquarkus.package.jar.type=fast-jar" package -Dnative'

install-native-window: build-native
    cp target/oprc-cli-{{version}}-runner.exe $HOME/.local/bin/ocli.exe
