= Oparaca CLI (OCLI)
:toc:
:toc-placement: preamble
:toclevels: 2

// Need some preamble to get TOC:
{empty}

The commandline interface for Oparaca.

== Installation

Download the executable file from the artifacts of GitHub Action buid (https://github.com/hpcclab/OaaS/actions/workflows/platform-container-build.yml[link]). They are usually in the bottom of summary page. Then, copy the executable file to any directory that assigned to PATH variable (ex. `/usr/local/bin`).

== Build from source

=== Native Image
The native image is preferable than the jar file because it has a much faster startup time. First, make sure to install the prerequisite programs for GraalVM. You can check on the prerequisites section of this link:https://quarkus.io/guides/building-native-image[guide].

[source,bash]
----
# FIRST BUILD MAIN PROJECT
./mvnw install -DskipTests
cd cli

# BUILD NATIVE IMAGE
just build-native
# OR
./mvnw install -Pnative -DskipTests
----
NOTE: For Windows user, there is some issue that the Microsoft Native Tools for Visual Studio must first be initialized before packaging. You can work around by run the following command instead: `just build-native-window`


Then, copy the output binary to any directory that assigned to PATH variable (ex. `/usr/local/bin`).

[source,bash]
----
# THEN COPY TO LOCAL BIN
cp target/oprc-cli-999-SNAPSHOT-runner $HOME/.local/bin/ocli
# OR IF YOU PREFER TO INSTALL AT SYSTEM LEVEL
sudo cp target/oprc-cli-999-SNAPSHOT-runner /usr/local/bin/ocli
# FOR WINDOW USER YOU CAN SIMPLY MOVE IT TO ANYWHERE THAT IS REGISTERED IN PATH VARIABLE
# FOR EXAMPLE
cp  target/oprc-cli-999-SNAPSHOT-runner.exe $HOME/.local/bin/ocli.exe
----


=== Jar file via JBang
You can install this cli by using https://www.jbang.dev/[jbang] and run the following command

[source,bash]
----
./mvnw package -DskipTests
cd cli
jbang app install --name=ocli --force target/oprc-cli-999-SNAPSHOT-runner.jar
----

== Usage
You can check the usage instruction by running `ocli -h`.

EXAMPLE
[source,bash]
----
# CONFIG THE CONNECTION
ocli ctx set --inv=http://inv.oaas.127.0.0.1.nip.io --pm=http://pm.oaas.127.0.0.1.nip.io
# DEPLOY PACKAGE
ocli p a example/pkg/record.yml
# CREATE OBJECT AND SAVE OBJECT ID FOR LATER USE (SAVE TO LOCAL CONFIG FILE)
ocli o c example.record -s
# INVOKE FUNCTION to a saved object
ocli i2 random
----
