"%test":
  quarkus:
    console:
      color: true
    log:
      min-level: TRACE
  oaas:
    log: TRACE

"%dev":
  quarkus:
    console:
      color: true
    http:
      port: 8088
  oaas:
    log: DEBUG


"%prod":
  oaas:
    oc:
      kafkaEnabled: true

oaas:
  oc:
    storageAdapterUrl: http://localhost:8093
    clsProvisionTopic: oaas-cls
    kafkaEnabled: false
    fnProvisionTopic: oaas-fn
  log: INFO
  name: object-controller

oprc:
  env: |
    OPRC_DB_OBJ_HOST=localhost
    OPRC_DB_OBJ_PORT=8529
    OPRC_DB_OBJ_USER=root
    OPRC_DB_PKG_HOST=localhost
    OPRC_DB_PKG_PORT=8529
    OPRC_DB_PKG_USER=root
    OPRC_DB_INV_HOST=localhost
    OPRC_DB_INV_PORT=8529
    OPRC_DB_INV_USER=root


quarkus:
  docker:
    dockerfile-jvm-path: src/main/docker/Dockerfile.jvm21
  http:
    access-log:
      enabled: true
      pattern: '"%r" %s %b %{RESPONSE_TIME} ms'
      exclude-pattern: /q/.*
    record-request-start-time: true
  vertx:
    prefer-native-transport: true
  swagger-ui:
    always-include: true
  smallrye-openapi:
    store-schema-directory: ../doc/oc
    enable: true
  log:
    category:
      "org.hpcclab.oaas":
        level: ${oaas.log}
  container-image:
    image: ${ci.registry.image:oaas}/${oaas.name}${tag:}
  jib:
    base-jvm-image: eclipse-temurin:17-jre-ubi9-minimal
  micrometer:
    export:
      json:
        enabled: true
        path: jsonmetrics
  native:
    resources:
      includes:
        - builtin/**
  rest-client:
    allocation-api:
      url: ${oaas.oc.storageAdapterUrl}
  kafka:
    devservices:
      enabled: false
mp:
  messaging:
    outgoing:
      fnProvisions:
        enabled: ${oaas.oc.kafkaEnabled}
        connector: smallrye-kafka
        topic: ${oaas.oc.fnProvisionTopic}
        value:
          serializer: io.quarkus.kafka.client.serialization.ObjectMapperSerializer
      clsProvisions:
        enabled: ${oaas.oc.kafkaEnabled}
        connector: smallrye-kafka
        topic: ${oaas.oc.clsProvisionTopic}
        value:
          serializer: io.quarkus.kafka.client.serialization.ObjectMapperSerializer
