= Package Definition References
:toc:
:toc-placement: preamble
:toclevels: 2

{empty}

== Package Structure

[source,yaml]
----
name: <name>
functions:
  - {function definitions}
  - {...}
classes:
  - {class definitions}
  - {...}
disabled:  <boolean if all classes in this package should be deployed>
----

== Class Definition
=== Structures and References

[source,yaml,linenumber]
----
classes:
  - name: <class name>
    disabled: <boolean if this class should be deployed> #  You can disabled class to use it as the template/parent class for other classes.
    stateType: <FILES or COLLECTION>
    stateSpec: # unstructured state declaration
      keySpecs:
        - name: <key name>
          access: <access modifier>
        - ...
    parents: # list of parent classes to inherit from
      - builtin.base
      - <parent class>
    functions: # List of instance function
      - name: <name of instance function> #this is for calling
        access: <access modifier>
        function: <<package.key> of the function> #This is for referencing the actual function definition
        outputCls: <<package.key> of output class> # overriding the output cls by function definition
        immutable: <boolean> #true for force immutable
        noMain: <boolean> #true for allowing the function to be called at class level (similar to static function in Java)
      - ...
----

In most cases, any classes should define <<builtin_base>> as the parent class (line 12) to inherit the list of built-in functions for normal operation (ex. create object). However, you can define those built-in function on your own.

=== Defining data of object
The data of object consist of two parts: *structured* data and *unstructured* data (BLOB).

For *structured* data, with the current state of Oparaca, it does not support the data schema for validation yet. You can simply store anything within the JSON format.
However, for the *unstructured* data, it is stored within the object storage, and its keys have to be predefined. The example of defining them are below.

[source, yaml]
----
  - name: <class name>
    stateSpec:
      keySpecs:
        - name: key1
        - name: key2
        - name: key3
----

== Function Definition

=== Structures and References
[source,yaml]
----
functions:
  - name: <function name>
    outputCls: <<package.key> of output class> # can be overridden by class definition
    description: <any description for this function> #Only for documenting
    type: <type of function [TASK, LOGICAL, MACRO, CHAIN] (default=CHAIN)>
    variableDescriptions: # args description for documenting purpose
      - name: <arg name>
        comment: <any comment>
    config:
      offloadingMode: <offloading mode [JSON, PROTOBUF, GRPC] (default=JSON)>
      custom: # dictionary of custom configuration that will be passed to the function (environment variable)
        <key>: <val>
    provision: # configure the engine for deploying this function
      knative: # if using Knative
        image: <container image tag>
        port: <port number of this container>

  - name: <function name>
    ...
    provision:
      deployment: # if using Kubernetes deployment
        image: <container image tag>
        replica: <number of pods>
        port: <port number>
        pullPolicy: <image pull policy> # set to 'IfNotPresent' to disable image pull if exists

  - name: <function name>
    ...
    provision:
      staticUrl: # if using nothing. Only if you host it on yourown.
        url: <url to function>

----


== Available built-in Functions

=== builtin.new
`builtin.new` is a function for creating object. When running the command `ocli object create`, the command will call `new` function.

NOTE: If the class doesn't have `new` function, object cannot be created via `ocli object create`.

=== builtin.update
`builtin.update` is a function for updating the object data from request body.

[source,bash]
----
oprc invoke update -d '{"name":"john","surname":"doe"}'
# the object data will be set to {"name":"john","surname":"doe"}
----

=== builtin.file
`builtin.file` is a function for generating a presign URL for unstructured data. When running the command `ocli object file`, the command will call `file` function.
NOTE: If the class doesn't have `new` function, you cannot load file in object via `ocli object file` or `ocli object cat-file`.

=== builtin.get
`builtin.file` is a function that return the output object as the  targeted of this function call. This function is made to be used in the dataflow.

Pseudo code for explanation:
----
obj = new Object()
output = obj.get()
assert output == obj
----

=== builtin.project
TODO

== Available built-in class

=== builtin.base [[builtin_base]]
The utility class to be inherited from. This class contains a list of built-in functions:

* builtin.new
* builtin.get
* builtin.file

== Dataflow Definitions

// === Chain functions

//
// [source, yaml]
// ----
//
// ----

=== Macro functions

To define the macro function, you have to add the function type to `MACRO` (line 2) and configure the parameters in `macro` field (line 3).

Generally, you need to define:

* `steps` for each step on invocation in this macro function.
* `output` for the output object of this macro function.
* `respBody` for the response body of this macro function.

The example of macro function of `record` class is below:
[source, yaml, lines]
----
  - name: <name>
    type: MACRO
    macro:
      steps:
        # var record1 = self.random()
        - target: '@'
          as: record1
          function: random
        # var record2 = record1.random()
        - target: record1
          as: record2
          function: random
        # var record3 = record2.random()
        - target: record2
          as: record3
          function: random
      # return record3
      output: record3
      # {step1: <record1>,step2: <record2>,step3: <record3>}
      bodyTemplate:
        step1: ${record1:output}
        step2: ${record2:output}
        step3: ${record3:output}
----

On each item in `steps`, we define:

* `target` is the target object for this invocation step. If it is the main object, you have to put `@`.
* `as` is the name of temporary output object. You can use this name as the invocation target in the later step.
* `function` is the name of function binding for invocation.
* `args` is the map (dictionary) of `args` for this invocation step.
* `bodyTemplate` is the request body for this invocation step.


To make this macro function return the object, you can set the `output` to the name of temporary output of any step.

To construct the response body, you can create the template with the data substitution from the result of any steps.


==== Data substitution

Example:
[source, yaml, lines]
----
  - name: <name>
    type: MACRO
    macro:
      steps:
        # var book = self.createBook(title=args['title'], author=args['author'])
        - target: '@'
          as: book
          function: createBook
          args:
            title: ${@|args|title}
            author: ${@|args|author}
          bodyTemplate:
            content: ${@|body|content}
            pages: ${@|body|page}
        # var store = self.assign(store=args['store'], bookId=book.bookId, bookPrice=book.price)
        - target: book
          as: store
          function: assign
          bodyTemplate:
            store: ${@|args|store}
            bookId: ${book|output|$.bookId}
            bookPrice: ${book|output|$.price}
      bodyTemplate:
        book: ${book|output}
        store: ${store|output}

----

