= Package Definition References
:toc:
:toc-placement: preamble
:toclevels: 2

{empty}

== Package Structure

[source,yaml]
----
name: <name>
functions:
  - {function definitions}
  - {...}
classes:
  - {class definitions}
  - {...}
disabled:  <boolean if all classes in this package should be deployed>
----

== Class Definition
=== Structures and References

[source,yaml,linenumber]
----
classes:
  - name: <class name>
    disabled: <boolean if this class should be deployed> #  You can disabled class to use it as the template/parent class for other classes.
    stateType: <FILES or COLLECTION>
    stateSpec: # unstructured state declaration
      keySpecs:
        - name: <key name>
          access: <access modifier>
        - ...
    parents: # list of parent classes to inherit from
      - builtin.base
      - <parent class>
    functions: # List of instance function
      - name: <name of instance function> #this is for calling
        access: <access modifier>
        function: <<package.key> of the function> #This is for referencing the actual function definition
        outputCls: <<package.key> of output class> # overriding the output cls by function definition
        immutable: <boolean> #true for force immutable
        noMain: <boolean> #true for allowing the function to be called at class level (similar to static function in Java)
      - ...
----

In most cases, any classes should define <<builtin_base>> as the parent class (line 12) to inherit the list of built-in functions for normal operation (ex. create object). However, you can define those built-in function on your own.

=== Defining data of object
The data of object consist of two parts: *structured* data and *unstructured* data (BLOB).

For *structured* data, with the current state of Oparaca, it does not support the data schema for validation yet. You can simply store anything within the JSON format.
However, for the *unstructured* data, it is stored within the object storage, and its keys have to be predefined. The example of defining them are below.

[source, yaml]
----
  - name: <class name>
    stateSpec:
      keySpecs:
        - name: key1
        - name: key2
        - name: key3
----

== Function Definition

=== Structures and References
[source,yaml]
----
functions:
  - name: <function name>
    outputCls: <<package.key> of output class> # can be overridden by class definition
    description: <any description for this function> #Only for documenting
    type: <type of function [TASK, LOGICAL, MACRO, CHAIN] (default=CHAIN)>
    variableDescriptions: # args description for documenting purpose
      - name: <arg name>
        comment: <any comment>
    config:
      offloadingMode: <offloading mode [JSON, PROTOBUF, GRPC] (default=JSON)>
      custom: # dictionary of custom configuration that will be passed to the function (environment variable)
        <key>: <val>
    provision: # configure the engine for deploying this function
      knative: # if using Knative
        image: <container image tag>
        port: <port number of this container>

  - name: <function name>
    ...
    provision:
      deployment: # if using Kubernetes deployment
        image: <container image tag>
        replica: <number of pods>
        port: <port number>
        pullPolicy: <image pull policy> # set to 'IfNotPresent' to disable image pull if exists

  - name: <function name>
    ...
    provision:
      staticUrl: # if using nothing. Only if you host it on yourown.
        url: <url to function>

----


== Available built-in Functions

=== builtin.new
`builtin.new` is a function for creating object. When running the command `ocli object create`, the command will call `new` function.

NOTE: If the class doesn't have `new` function, object cannot be created via `ocli object create`.

=== builtin.update
`builtin.update` is a function for updating the object data from request body.

[source,bash]
----
oprc invoke update -d '{"name":"john","surname":"doe"}'
# the object data will be set to {"name":"john","surname":"doe"}
----

=== builtin.file
`builtin.file` is a function for generating a presign URL for unstructured data. When running the command `ocli object file`, the command will call `file` function.
NOTE: If the class doesn't have `new` function, you cannot load file in object via `ocli object file` or `ocli object cat-file`.

=== builtin.get
`builtin.file` is a function that return the output object as the  targeted of this function call. This function is made to be used in the dataflow.

Pseudo code for explanation:
----
obj = new Object()
output = obj.get()
assert output == obj
----

=== builtin.project
TODO

== Available built-in class

=== builtin.base [[builtin_base]]
The utility class to be inherited from. This class contains a list of built-in functions:

* builtin.new
* builtin.get
* builtin.file

== Dataflow Definitions

=== Chain functions
TODO

[source, yaml]
----

----

=== Macro functions
TODO

[source, yaml]
----

----
