---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: class-runtime-manager-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: class-runtime-manager-role
rules:
  - apiGroups: ["serving.knative.dev"]
    resources: ["services"]
    verbs: ["get", "list", "update", "watch", "patch", "create", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "update", "watch", "patch", "create", "delete"]
  - apiGroups: [""]
    resources: ["secrets", "configmaps", "services", "pods"]
    verbs: ["get", "list", "update", "watch", "patch", "create", "delete"]
  - apiGroups: ["monitoring.coreos.com"]
    resources: ["podmonitors"]
    verbs: ["get", "list", "update", "watch", "create", "patch", "delete"]
  - apiGroups: ["autoscaling"]
    resources: ["horizontalpodautoscalers"]
    verbs: ["get", "list", "update", "watch", "create", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: class-runtime-manager-cluster-role
rules:
  - apiGroups: ["metrics.k8s.io"]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["nodes", "pods"]
    verbs: ["get", "list", "watch"]
---

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: class-runtime-manager-rb
roleRef:
  kind: Role
  name: class-runtime-manager-role
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: class-runtime-manager-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: class-runtime-manager-crb
roleRef:
  kind: ClusterRole
  name: class-runtime-manager-cluster-role
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: class-runtime-manager-sa
    namespace: oaas
