resources:
  - env-configmap.yml
### kube-provisioner
  - orbit-manager.yml
  - orbit-manager-rb.yml
### object-controller
  - class-manager.yml
### content-delivery-service
  - cds.yml
### storage adapter
  - sa.yml
### invoker
  - invoker-svc.yml
#  - invoker-hpa.yml

