templates:
  default:
    type: "default"
    condition: { }
    services:
      invoker:
        image: ghcr.io/hpcclab/oaas/invoker
        imagePullPolicy: IfNotPresent
        stabilizationWindow: 120000
        maxScaleStep: 2
        env:
          OPRC_INVOKER_NUMOFVERTICLE: "1"
          OPRC_INVOKER_NUMOFINVOKERVERTICLE: "2"
          OPRC_LOG: "DEBUG"
#          QUARKUS_HTTP_ACCESS_LOG_ENABLED: "false"
        requestCpu: '1'
        requestMemory: 1Gi
        limitCpu: '2'
        limitMemory: 2Gi
        maxReplicas: 20
        objectiveMissThreshold: 0.4
      storage-adapter:
        image: ghcr.io/hpcclab/oaas/storage-adapter
        imagePullPolicy: IfNotPresent
        stabilizationWindow: 30000
        maxScaleStep: 2
        env:
          OPRC_LOG: "DEBUG"
        requestCpu: 500m
        requestMemory: 256Mi
        limitCpu: '2'
        limitMemory: 1Gi
        maxReplicas: 20
        objectiveMissThreshold: 0.4
    optimizerConf:
      thresholdUpper: 0.95
      thresholdLower: 0.5
    functions:
      stabilizationWindow: 30000
      maxScaleStep: 3
      defaultRequestCpu: 500m
      defaultRequestMem: 256Mi
    priority: 0
  ######################################################
  high-load:
    condition:
      path: "$.qos.throughput"
      op: GT
      val: "1000"
    type: "default"
    services:
      invoker:
        image: ghcr.io/hpcclab/oaas/invoker
        imagePullPolicy: IfNotPresent
        stabilizationWindow: 120000
        maxScaleStep: 1
        env:
          OPRC_INVOKER_NUMOFVERTICLE: "2"
          OPRC_INVOKER_NUMOFINVOKERVERTICLE: "2"
          OPRC_LOG: "WARN"
        requestCpu: '4'
        requestMemory: 2Gi
        limitCpu: '4'
        limitMemory: 4Gi
        maxReplicas: 20
        objectiveMissThreshold: 0.4
        startReplicasToTpRatio: 0.00005
      storage-adapter:
        image: ghcr.io/hpcclab/oaas/storage-adapter
        imagePullPolicy: IfNotPresent
        stabilizationWindow: 30000
        maxScaleStep: 1
        env:
          OPRC_LOG: "DEBUG"
        requestCpu: '2'
        requestMemory: 512Mi
        limitCpu: '2'
        limitMemory: 2Gi
        maxReplicas: 20
        objectiveMissThreshold: 0.4
        startReplicasToTpRatio: 0.00005
    optimizerConf:
      thresholdUpper: 0.8
      thresholdLower: 0.5
    functions:
      stabilizationWindow: 30000
      maxScaleStep: 5
      defaultRequestCpu: 500m
      defaultRequestMem: 256Mi
    priority: 10
