{
 "title": "Oparaca",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "crId",
    "label": "CR",
    "query": {
     "query": "label_values(oprc_invocation_seconds_count,crId)"
    }
   },
   { "name": "percentile", "query": "0.99,0.95,0.7,0.5" }
  ]
 },
 "panels": [
  { "title": "Total CPU and Memory Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Memory Usage ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (container_memory_usage_bytes{pod=~\"cr-$crId-.*\"})",
     "legendFormat": "$crId"
    }
   ]
  },
  {
   "title": "Total CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum (rate(container_cpu_usage_seconds_total{pod=~\"cr-$crId-.*\"}[1m]))",
     "legendFormat": "$crId"
    }
   ]
  },
  { "title": "Per Pod CPU and Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Memory Usage (core)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_usage_bytes{pod=~\"cr-$crId-invoker.*\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (pod) (container_memory_usage_bytes{pod=~\"cr-$crId-storage-adapter.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage (core)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{pod=~\"cr-$crId-invoker.*\"}[1m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{pod=~\"cr-$crId-storage-adapter.*\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage (functions)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_usage_bytes{pod=~\"cr-$crId-fn.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage (functions)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{pod=~\"cr-$crId-fn-.*\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Invocation Rate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Invoker requests per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (crId) (rate(oprc_invocation_seconds_count{crId=~\"$crId\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Function (requests per second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (crId,func) (rate(oprc_invocation_seconds_count{crId=~\"$crId\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 }, "repeat": "percentile" },
  {
   "title": "Invocation Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(${percentile:raw}, sum by (crId, le) (rate(oprc_invocation_seconds_bucket{crId=~\"$crId\"}[1m])))",
     "legendFormat": "{{ crId }} (${percentile:raw})"
    }
   ]
  },
  {
   "title": "Invocation Time per Function",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(${percentile:raw}, sum by (crId, func, le) (rate(oprc_invocation_seconds_bucket{crId=~\"$crId\"}[1m])))",
     "legendFormat": "{{ crId }}-{{func}} (${percentile:raw})"
    }
   ]
  }
 ]
}