resources:
  - ../local

patches:
  - target:
      version: v1
      kind: Deployment
      name: object-controller
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Never
  - target:
      version: v1
      kind: Deployment
      name: kube-provisioner
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Never
  - target:
      version: v1
      kind: Deployment
      name: storage-adapter
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Never
  - target:
      version: v1
      kind: Deployment
      name: invoker
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Never
