
"%dev":
  quarkus:
    http:
      port: 8091
    log:
      category:
        "org.hpcclab.oaas":
          level: DEBUG

oaas:
  kp:
    fnProvisionTopic: oaas-fn
    clsProvisionTopic: oaas-cls
    exposeKnative: false
  orbit:
    oparacaManagerHost: localhost
    oparacaManagerPort: 8088
  log: INFO
  name: orbit-manager

quarkus:
  log:
    category:
      "org.hpcclab.oaas":
        level: ${oaas.log}
  http:
    access-log:
      enabled: true
      exclude-pattern: /q/.*
  vertx:
    prefer-native-transport: true
  container-image:
    image: ${ci.registry.image:oaas}/${oaas.name}${tag:}
  console:
    color: true

  grpc:
    clients:
      oparaca-manager:
        use-quarkus-grpc-client: true
        host: ${oaas.orbit.oparacaManagerHost}
        port: ${oaas.orbit.oparacaManagerPort}
mp:
  messaging:
    outgoing:
      fnUpdated:
        connector: smallrye-kafka
        topic: ${oaas.kp.fnProvisionTopic}
        merge: true
      clsUpdated:
        connector: smallrye-kafka
        topic: ${oaas.kp.clsProvisionTopic}
    incoming:
      fnProvisions:
        connector: smallrye-kafka
        topic: ${oaas.kp.fnProvisionTopic}
        auto:
          offset:
            reset: earliest
      clsProvisions:
        connector: smallrye-kafka
        topic: ${oaas.kp.clsProvisionTopic}
        auto:
          offset:
            reset: earliest
