
"%dev":
  quarkus:
    http:
      port: 8091
    log:
      category:
        "org.hpcclab.oaas":
          level: DEBUG
    kubernetes-client:
      namespace: oaas
oaas:
  om:
    exposeKnative: false
  orbit:
    clsManagerHost: localhost
    clsManagerPort: 8088
  log: INFO
  name: orbit-manager

quarkus:
  log:
    category:
      "org.hpcclab.oaas":
        level: ${oaas.log}
  http:
    access-log:
      enabled: true
      exclude-pattern: /q/.*
  vertx:
    prefer-native-transport: true
  container-image:
    image: ${ci.registry.image:oaas}/${oaas.name}${tag:}
  console:
    color: true

  grpc:
    clients:
      class-manager:
        use-quarkus-grpc-client: true
        host: ${oaas.orbit.clsManagerHost}
        port: ${oaas.orbit.clsManagerPort}

    server:
      enable-reflection-service: true
      use-separate-server: false

