"%test":
  quarkus:
    console:
      color: true
    log:
      min-level: TRACE
    kafka:
      devservices:
        port: 9092
  oprc:
    log: TRACE
    invoker:
      kafka: localhost:9092
      loadMode: disabled
    crid: "placeholer"

"%dev":
  quarkus:
    http:
      port: 8089
    devservices:
      enabled: false
  oprc:
    log: DEBUG
    invoker:
      kafka: PLAINTEXT://localhost:19092
      sa:
        url: http://localhost:8090
      s3:
        url: http://localhost:9000
        publicUrl: http://localhost:9000
        bucket: oaas
        accessKey: minio_access_key
        secretKey: minio_access_key
      useSa: false
      clusterLock: true
      loadMode: disabled

oprc:
  log: INFO
  name: invoker
  invoker:
    sa:
      url: http://localhost:8090
    pmHost: localhost
    pmPort: 8088
  ispn:
    objStore:
      maxCount: 1000000
      queueSize: 1000000
      storageType: OFF_HEAP
    clsStore:
      maxCount: 10000
      storageType: HEAP
    fnStore:
      maxCount: 10000
      storageType: HEAP
  env: |
    OPRC_DB_PKG_HOST=localhost
    OPRC_DB_PKG_PORT=8529
    OPRC_DB_PKG_USER=root
    OPRC_DB_DEFAULT_HOST=localhost
    OPRC_DB_DEFAULT_PORT=8529
    OPRC_DB_DEFAULT_USER=root
    OPRC_DB_INV_HOST=localhost
    OPRC_DB_INV_PORT=8529
    OPRC_DB_INV_USER=root
    OPRC_DB_S3DEFAULT_URL=http://localhost:9000
    OPRC_DB_S3DEFAULT_BUCKET=oaas-bkt
    OPRC_DB_S3DEFAULT_PUBLICURL=http://localhost:9000
    OPRC_DB_S3DEFAULT_USER=minio_access_key
    OPRC_DB_S3DEFAULT_PASS=minio_secret_key

quarkus:
  grpc:
    server:
      use-separate-server: false
    clients:
      package-manager:
        host: ${oprc.invoker.pmHost}
        port: ${oprc.invoker.pmPort}

  s3:
    devservices:
      enabled: false
  naming:
    enable-jndi: true
  console:
    color: false
  http:
    access-log:
      enabled: true
      pattern: '"%r" %s %b %{RESPONSE_TIME} ms'
      exclude-pattern: /q/.*
    record-request-start-time: true
  vertx:
    prefer-native-transport: true
  log:
    category:
      "org.hpcclab.oaas":
        level: ${oprc.log}
  container-image:
    image: ${ci.registry.image:oaas}/${oprc.name}${tag:}
  micrometer:
    export:
      json:
        enabled: true
        path: jsonmetrics
