"%test":
  quarkus:
    console:
      color: true
    log:
      min-level: TRACE
    kafka:
      devservices:
        port: 9092
  oaas:
    log: TRACE
    invoker:
      kafka: localhost:9092
      storageAdapterUrl: "http://localhost:8000"

"%dev":
  quarkus:
    http:
      port: 8089
    devservices:
      enabled: false
  oaas:
    log: DEBUG
    invoker:
      kafka: PLAINTEXT://localhost:19092
      storageAdapterUrl: http://localhost:8090
      s3:
        url: http://localhost:9000
        publicUrl: http://localhost:9000
        bucket: oaas
        accessKey: minio_access_key
        secretKey: minio_access_key
      useSa: false
      clusterLock: true
    ispn:
      argConnection:
        host: localhost
        port: 8529
        user: root
        pass: changeme
        db: oaas


oaas:
  log: INFO
  name: invoker
  ispn:
    objStore:
      maxCount: 1000000
      queueSize: 1000000
      storageType: OFF_HEAP
    clsStore:
      maxCount: 10000
      storageType: HEAP
    fnStore:
      maxCount: 10000
      storageType: HEAP


quarkus:
  s3:
    devservices:
      enabled: false
  naming:
    enable-jndi: true
  console:
    color: true
  http:
    access-log:
      enabled: true
      pattern: '"%r" %s %b %{RESPONSE_TIME} ms'
      exclude-pattern: /q/.*
    record-request-start-time: true
  vertx:
    prefer-native-transport: true
  log:
    category:
      "org.hpcclab.oaas":
        level: ${oaas.log}
  container-image:
    image: ${ci.registry.image:oaas}/${oaas.name}${tag:}
  jib:
    base-jvm-image: eclipse-temurin:17-jre-ubi9-minimal
    jvm-arguments: -Djava.util.logging.manager=org.jboss.logmanager.LogManager
  micrometer:
    export:
      json:
        enabled: true
        path: jsonmetrics
